### ISSUE TITLE
Refactor: certain websites include the same json.

### ISSUE THREAD

**Issue by jerjou** [poundifdef/plainoldrecipe#18]
These parsers all seem to do essentially the same thing:
* bowlofdelicious
* gimmesomeoven
* hostthetoast
* lovingitvegan
* minimalistbaker

I'd like to add thewoksoflife.com which includes the same json. Ideally I could just add it to a whitelist or something, instead of copying a lot of boilerplate.

Alternatively, since the format seems to be fairly common, you could potentially grab the html, attempt to scrape it, and only if that fails you would show the unsupported page.

**Comment by bfcarpio** [comment]
I'm in the process of migrating the parsers you listed into https://github.com/hhursev/recipe-scrapers which is a dependency of this repo and already has an abstraction made.

So far I have this one: hhursev/recipe-scrapers#177

I'll submit a PR to this repo removing the parsers when I'm done. 

Feel free to start at the bottom of the list and work up.

**Comment by poundifdef** [comment]
Hi @jerjou - I like this idea! Would you like to work together to make it a reality?

**Comment by jerjou** [comment]
Sure? I wouldn't want to get in the way of any works in progress, though..?

**Comment by bfcarpio** [comment]
There is also another [package](https://github.com/micahcochran/scrape-schema-recipe) that supports generic scraping of Schema websites. Might be easier to just incorporate that one?

**Comment by jerjou** [comment]
I agree that's a better solution.

**Comment by bfcarpio** [comment]
[This](https://github.com/boonepeter/recipe-parser) project seems to have a good system for using the above linked package and a package already included within `plainoldrecipe`.

> This is a flask server that serves an API that accepts recipe urls and returns a parsed recipe. Uses scrape-schema-recipe then falls back on recipe-scrapers.

That type of design could be copied to reduce the processing in this repo.

**Comment by poundifdef** [comment]
I have no objection to using `scrape-schema-recipe`. 

I do prefer to have a whitelist of websites - even if that whitelist simply points to a library to parse the recipe. This is to prevent abuse; I don't want the public version of this code to be able to download any arbitrary URL, I only want it to download pre-defined websites.

That said, perhaps the behavior could be a feature-flag: enforce a whitelist in "production" mode, as not to invite malicious users to the websites, but have that whitelist disabled in other contexts.

Also, I know I'm pending looking at updates and PRs that the two of you have made, so I will get to that!

**Comment by bfcarpio** [comment]
@poundifdef I'm not sure if I entirely understand you. Are you worried about someone trying to put `maliciousurl.com` into the deployed instance?

From a quick look at `scrape-schema-recipe` it seems to only return a [schema.org recipe](https://schema.org/Recipe) compliant dictionary. I know for a fact that `recipe-scrapers` only returns a similar recipe oriented shape as well.

So unless `maliciousurl.com` has a recipe schema for something gross I don't think your page will display anything. Likely, it'll just give the same old "site is not implemented" error.

**Comment by poundifdef** [comment]
Two concerns. One is what you state: can I only retrieve websites which are "known" to have legitimate recipes, without malicious payloads? Second, my concern is "Could a bad actor use plainoldrecipe.com to send traffic to any arbitrary website?" As a maintainer of the service, I want to be able to control exactly _to whom_ my servers are making HTTP requests.

This, of course, would not prevent someone from using plainoldrecipe.com to repeatedly hit a whitelisted URL. If that happens, I'd need to update the code to have some protection here.

If this site had stronger protections against spammy users (user accounts, CAPTCHA, rate limiting, or even having the client request the website in their browser and then transmit the HTML to the server for parsing - may options here!) then I'd be fine with removing the whitelist, but those features do not exist today.

I also realize that this a inconvenient for users of plainoldrecipe.com, who may want to be able to parse websites which use the JSON schema without a code change. That is why I suggest a feature flag for this behavior, so that those who choose to host themselves, or run the service locally, can use a less restricted version.

**Comment by bfcarpio** [comment]
> One is what you state: can I only retrieve websites which are "known" to have legitimate recipes, without malicious payloads?

I'm not sure if this is an issue for `plainoldrecipe`. We already know that only a subset of websites will return a non-error payload since we use parsers or scraping packages. This means we need to trust the scraping packages and can do so since they are open source. 

From there, I don't know what malicious action they can take against `plainoldrecipe` since you don't store the response in state. You merely shove it in a template and send it off. The data is never used again and no further processing is done based of this data.

Finally, a user had to consent to putting a website URL into `plainoldrecipe` which means they are expecting some sort of response. For my usage, I go to the original recipe page, check to see if I'm interested in making it, and then use `plainoldrecipe`. If the recipe page was suspect I would have been exposed via the original page anyways.

> Second, my concern is "Could a bad actor use plainoldrecipe.com to send traffic to any arbitrary website?"

I see this as a very valid point...

I personally use a bash script I found on reddit to interface with `plainoldrecipe`. It uses `cUrl` to send the recipe URL and then reformats the cleaned HTML into markdown (my preferred format). Captchas would be annoying. User accounts would make me consider not using the service, but could be done with headers. A rate limit wouldn't be *too* bad. Maybe 3 seconds or 10 requests a minute? Something like that wouldn't be too bad for a "real" user or even someone scripting with a small amount of recipes (meal planning for the week).

It might help recipe websites if the requests use a description user-agent such as "plainoldrecipe.com" or "support@plainoldrecipe.com".

> That is why I suggest a feature flag for this behavior, so that those who choose to host themselves, or run the service locally, can use a less restricted version.

Yeah, some sort of config file with "production" defaults would work fine for your instance and could be easily modified by others.

**Comment by poundifdef** [comment]
Merged PR #19 , resolving this
