### ISSUE TITLE
Serious eats includes an extra number on the list of steps 

### ISSUE THREAD

**Issue by Dgaduin** [poundifdef/plainoldrecipe#7]
E.g. https://plainoldrecipe.com/recipe?url=https%3A%2F%2Fwww.seriouseats.com%2Frecipes%2F2016%2F04%2Fno-knead-english-muffins-recipe.html

![image](https://user-images.githubusercontent.com/2265194/85908349-a1175280-b80c-11ea-8ac2-1d77e73957a9.png)

**Comment by poundifdef** [comment]
Thank you for raising this! Might you be interested in making a small pull request to implement a fix? I feel like, for Serious Eats, one would just need to remove the beginning few characters which match this pattern.

**Comment by spkuehl** [comment]
Is it better to open a ticket in the 3rd party library [recipe-scraper](https://github.com/hhursev/recipe-scrapers), or to make a custom fix here?

**Comment by poundifdef** [comment]
That's a good question! I'm fine either way. If they are receptive to the change, and then your PR here is simply to update the package version, then that works for me. But if that is too much trouble and you want to fix here then I'm equally fine with that.

If you do fix it here, you may have to make an additional modification: currently, we check to see whether the library supports the website first, and if not, then we use the code in this repo. You'd have to reverse the order of that check so that any code in this repo takes precedence. Not a big change, just something to keep in mind.

**Comment by poundifdef** [comment]
This has been fixed now :)
